Add workflow to check for uncommitted but changed pot files

diff --git a/.github/workflows/pull.yaml b/.github/workflows/pull.yaml
--- a/.github/workflows/pull.yaml
+++ b/.github/workflows/pull.yaml
@@ -18,7 +18,7 @@ jobs:
           node-version: 20
           cache: npm
       - name: install deps
-        run: npm ci && zypper install -y cockpit-devel make
+        run: npm ci && zypper install -y cockpit-devel make gettext-tools
       - name: add cockpit-tukit as a safe safe directory
         run: git config --global --add safe.directory /__w/cockpit-tukit/cockpit-tukit
       - name: build
@@ -27,3 +27,14 @@ jobs:
         run: npm run ci
       - name: typecheck
         run: npm run typecheck
+      - name: pot file changed but not commited
+        run: |
+          touch org.cockpit-project.tukit.metainfo.xml src/index.tsx
+          make po/tukit.pot
+          git --no-pager diff po/tukit.pot
+          [ "$(git diff --numstat po/tukit.pot | cut -f1)" -gt 2 ] || \
+          [ "$(git diff --numstat po/tukit.pot | cut -f2)" -gt 2 ] \
+            && echo "po/tukit.pot has changed. Failing test" \
+            && exit 1
+          echo "No changes other than expected timestamps"
+          exit 0
